# Generated by Django 4.2.7 on 2023-12-11 07:00

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('teammember', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='excerpt',
            new_name='firstName',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='author',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='title',
        ),
        migrations.AddField(
            model_name='teammember',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='is_Admin',
            field=models.BooleanField(default=False, verbose_name='Admin'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='is_Regular',
            field=models.BooleanField(default=False, verbose_name='Regular'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='lastName',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
