# Generated by Django 4.2.7 on 2023-12-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammember', '0002_rename_excerpt_teammember_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='firstName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='lastName',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
